services:
  - type: web
    name: usaau
    env: python
    buildCommand: ""
    startCommand: gunicorn project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: "3.10"
    plan: free
