# Generated by Django 5.2 on 2025-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان المغامرة')),
                ('description', models.TextField(verbose_name='وصف المغامرة')),
                ('image', models.ImageField(upload_to='adventures/', verbose_name='صورة المغامرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مغامرة',
                'verbose_name_plural': 'مغامرات',
            },
        ),
    ]
