# Generated by Django 5.2 on 2025-04-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities/gallery/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='pages.city')),
            ],
        ),
    ]
