# Generated by Django 5.2 on 2025-04-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Adventure',
        ),
    ]
